# Generated by Django 6.0.5 on 2026-08-31 09:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0010_hrprofile_perm_cantine_read_and_more'),
        ('employees', '0019_cantinelist_cantinelistitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('prenom', models.CharField(max_length=150)),
                ('telephone', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('date_candidature', models.DateField(default=django.utils.timezone.localdate)),
                ('source', models.CharField(blank=True, max_length=200)),
                ('fiche_test', models.FileField(blank=True, null=True, upload_to='recrutement/fiches-test/')),
                ('statut', models.CharField(choices=[('NON_RECU', 'Non reçu'), ('RECU', 'Reçu'), ('EMBAUCHE', 'Embauché')], default='NON_RECU', max_length=20)),
                ('observations', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='DemandeRecrutement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=30, unique=True)),
                ('matricule_demandeur', models.CharField(max_length=100)),
                ('nom_demandeur', models.CharField(max_length=255)),
                ('poste_demandeur', models.CharField(max_length=150)),
                ('departement_demandeur', models.CharField(max_length=150)),
                ('nombre_cdi', models.PositiveIntegerField(default=0)),
                ('nombre_cdd', models.PositiveIntegerField(default=0)),
                ('date_prevue_recrutement', models.DateField()),
                ('motif', models.CharField(choices=[('DEMISSION', 'Démission'), ('LICENCIEMENT', 'Licenciement'), ('DECES', 'Décès'), ('REMPLACEMENT', 'Remplacement')], max_length=20)),
                ('designation_taches', models.TextField(blank=True)),
                ('profil_diplome', models.TextField(blank=True)),
                ('experience_professionnelle', models.TextField()),
                ('competences_techniques', models.TextField()),
                ('savoir_faire', models.TextField()),
                ('savoir_etre', models.TextField()),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EN_ATTENTE', 'En attente'), ('VALIDEE', 'Validée'), ('REFUSEE', 'Refusée'), ('TERMINEE', 'Terminée')], default='EN_ATTENTE', max_length=20)),
                ('motif_decision', models.TextField(blank=True)),
                ('date_decision', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('decide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions_recrutement', to='accounts.hrprofile')),
                ('demandeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_recrutement', to='accounts.hrprofile')),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes_recrutement', to='employees.department')),
                ('employe_a_remplacer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_de_remplacement', to='employees.employee')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes_recrutement', to='employees.factory')),
                ('poste', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes_recrutement', to='employees.poste')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Embauche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_contrat', models.CharField(choices=[('CDI', 'CDI'), ('CDD', 'CDD')], max_length=20)),
                ('date_debut_contrat', models.DateField()),
                ('contrat_signe', models.FileField(blank=True, null=True, upload_to='recrutement/contrats/')),
                ('remarque_generale', models.TextField(blank=True)),
                ('date_confirmation', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('candidat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embauche', to='recruitment.candidat')),
                ('employe', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='embauche_recrutement', to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessusRecrutement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etape_actuelle', models.PositiveSmallIntegerField(default=1)),
                ('etapes_terminees', models.JSONField(blank=True, default=list)),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('TERMINE', 'Terminé')], default='EN_COURS', max_length=20)),
                ('fichier_suivi', models.FileField(blank=True, null=True, upload_to='recrutement/suivi/')),
                ('liste_candidats_confirmee', models.BooleanField(default=False)),
                ('observations_suivi', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('demande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='processus', to='recruitment.demanderecrutement')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='OffreRecrutement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('lieu_travail', models.CharField(choices=[('SITE_1', 'Site 1'), ('SITE_2', 'Site 2'), ('SITE_3', 'Site 3')], max_length=20)),
                ('date_limite_candidature', models.DateField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('processus', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offre', to='recruitment.processusrecrutement')),
            ],
        ),
        migrations.CreateModel(
            name='FicheTransparence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='recrutement/transparence/')),
                ('observations', models.TextField(blank=True)),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('processus', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fiche_transparence', to='recruitment.processusrecrutement')),
            ],
        ),
        migrations.AddField(
            model_name='candidat',
            name='processus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidats', to='recruitment.processusrecrutement'),
        ),
        migrations.CreateModel(
            name='PublicationOffre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(max_length=150)),
                ('date_publication', models.DateField()),
                ('lien', models.URLField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('processus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='recruitment.processusrecrutement')),
            ],
            options={
                'ordering': ['date_publication', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RetourRHCandidat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsable_rh', models.CharField(max_length=255)),
                ('date_remise_liste', models.DateField(default=django.utils.timezone.localdate)),
                ('liste_imprimee', models.BooleanField(default=False)),
                ('liste_remise', models.BooleanField(default=False)),
                ('remarque', models.TextField(blank=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('candidat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='retour_rh', to='recruitment.candidat')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentCandidat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
                ('recu', models.BooleanField(default=False)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='recrutement/documents-candidats/')),
                ('remarque', models.TextField(blank=True)),
                ('retour_rh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='recruitment.retourrhcandidat')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='demanderecrutement',
            index=models.Index(fields=['statut'], name='recrutement_statut_idx'),
        ),
        migrations.AddIndex(
            model_name='demanderecrutement',
            index=models.Index(fields=['departement', 'statut'], name='recrutement_dept_statut_idx'),
        ),
        migrations.AddConstraint(
            model_name='candidat',
            constraint=models.UniqueConstraint(condition=models.Q(('email', ''), _negated=True), fields=('processus', 'email'), name='unique_email_candidat_processus'),
        ),
    ]
