# Generated by Django 6.0.5 on 2026-08-31 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demanderecrutement',
            name='employe_a_remplacer',
        ),
        migrations.AddField(
            model_name='demanderecrutement',
            name='motif_remplacement',
            field=models.CharField(blank=True, choices=[('FIN', 'Fin de période d’essai'), ('DEMISSION', 'Démission'), ('ABANDON', 'Abandon de poste'), ('LICENCIEMENT', 'Licenciement'), ('INAPTITUDE', 'Inaptitude'), ('RETRAITE', 'Départ à la retraite'), ('FIN_CDD', 'Fin de CDD / non-renouvellement de CDD'), ('RUPTURE', 'Rupture conventionnelle'), ('MUTATION', 'Mutation / mobilité interne'), ('PROMOTION', 'Promotion ou changement de poste'), ('MATERNITE', 'Congé maternité'), ('DECES', 'Décès')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='demanderecrutement',
            name='motif',
            field=models.CharField(choices=[('RAJOUT', 'Rajout d’effectif'), ('CREATION', 'Création de poste'), ('REMPLACEMENT', 'Remplacement')], max_length=20),
        ),
    ]
