# Generated by Django 6.0.5 on 2026-09-01 08:35

import django.db.models.deletion
import recruitment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_remove_demanderecrutement_employe_a_remplacer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offrerecrutement',
            options={'ordering': ['-date_creation']},
        ),
        migrations.RemoveField(
            model_name='offrerecrutement',
            name='date_limite_candidature',
        ),
        migrations.RemoveField(
            model_name='offrerecrutement',
            name='description',
        ),
        migrations.RemoveField(
            model_name='offrerecrutement',
            name='lieu_travail',
        ),
        migrations.RemoveField(
            model_name='offrerecrutement',
            name='processus',
        ),
        migrations.AddField(
            model_name='offrerecrutement',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='offrerecrutement',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to=recruitment.models.chemin_fichier_offre),
        ),
        migrations.AddField(
            model_name='offrerecrutement',
            name='nom_fichier_original',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='offrerecrutement',
            name='reference',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='processusrecrutement',
            name='offre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processus_recrutement', to='recruitment.offrerecrutement'),
        ),
        migrations.AlterField(
            model_name='offrerecrutement',
            name='titre',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
