# Generated by Django 6.0.5 on 2026-09-01 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0003_alter_offrerecrutement_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicationoffre',
            name='lien',
        ),
        migrations.AddField(
            model_name='publicationoffre',
            name='commentaire',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='publicationoffre',
            name='date_limite_candidature',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publicationoffre',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='publicationoffre',
            name='lien_ou_reference',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='publicationoffre',
            name='preuve',
            field=models.FileField(blank=True, null=True, upload_to='recruitment/publications/'),
        ),
        migrations.AddConstraint(
            model_name='publicationoffre',
            constraint=models.UniqueConstraint(fields=('processus',), name='unique_publication_par_processus'),
        ),
    ]
