# Generated by Django 6.0.5 on 2026-09-01 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0004_remove_publicationoffre_lien_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fichetransparence',
            options={'ordering': ['-date_upload']},
        ),
        migrations.AddField(
            model_name='fichetransparence',
            name='date_fiche',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fichetransparence',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='fichetransparence',
            name='lieu',
            field=models.CharField(blank=True, choices=[('SITE_1', 'PBI 1'), ('SITE_2', 'PBI 2'), ('SITE_3', 'PBI 3')], max_length=20),
        ),
        migrations.AddField(
            model_name='fichetransparence',
            name='original_signe',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fichetransparence',
            name='fichier',
            field=models.FileField(upload_to='recruitment/transparence/'),
        ),
    ]
