# Generated by Django 6.0.5 on 2026-09-01 12:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0005_alter_fichetransparence_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='embauche',
            options={'ordering': ['-date_creation']},
        ),
        migrations.RemoveField(
            model_name='embauche',
            name='contrat_signe',
        ),
        migrations.AddField(
            model_name='embauche',
            name='date_verification',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='embauche',
            name='signe_candidat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='embauche',
            name='signe_employeur',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='embauche',
            name='verificateur',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='embauche',
            name='remarque_generale',
            field=models.TextField(blank=True, default=''),
        ),
    ]
