# Generated by Django 6.0.5 on 2026-09-02 05:32

import django.db.models.deletion
import recruitment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_hrprofile_perm_cantine_read_and_more'),
        ('recruitment', '0006_alter_embauche_options_remove_embauche_contrat_signe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demanderecrutement',
            name='type_recrutement',
            field=models.CharField(choices=[('OUVRIER', 'Ouvrier'), ('CADRE', 'Cadre')], db_index=True, default='OUVRIER', max_length=20),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='statut',
            field=models.CharField(choices=[('AJOUTE', 'Ajouté'), ('ENTRETIEN_PLANIFIE', 'Entretien planifié'), ('COMPTE_RENDU_BROUILLON', 'Compte rendu en brouillon'), ('COMPTE_RENDU_ENVOYE', 'Compte rendu envoyé'), ('RETENU', 'Retenu'), ('NON_RETENU', 'Non retenu'), ('NON_RECU', 'Non reçu'), ('RECU', 'Reçu'), ('EMBAUCHE', 'Embauché')], default='AJOUTE', max_length=30),
        ),
        migrations.CreateModel(
            name='CompteRenduEntretienCadre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default=recruitment.models.generer_reference_compte_rendu, editable=False, max_length=40, unique=True)),
                ('date_entretien', models.DateField(blank=True, null=True)),
                ('poste', models.CharField(blank=True, default='', max_length=255)),
                ('pretention_salariale', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('devise', models.CharField(choices=[('MGA', 'MGA'), ('EUR', 'EUR'), ('USD', 'USD')], default='MGA', max_length=10)),
                ('disponibilite', models.CharField(blank=True, default='', max_length=100)),
                ('precision_disponibilite', models.CharField(blank=True, default='', max_length=255)),
                ('annees_experience', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('diplome', models.CharField(blank=True, default='', max_length=255)),
                ('etablissement', models.CharField(blank=True, default='', max_length=255)),
                ('redacteur_rh', models.BooleanField(default=False)),
                ('redacteur_manager', models.BooleanField(default=False)),
                ('avis_rh', models.CharField(blank=True, choices=[('FAVORABLE', 'Favorable'), ('FAVORABLE_RESERVE', 'Favorable avec réserve'), ('DEFAVORABLE', 'Défavorable'), ('A_REVOIR', 'À revoir')], default='', max_length=30)),
                ('commentaire_rh', models.TextField(blank=True, default='')),
                ('nom_signataire_rh', models.CharField(blank=True, default='', max_length=255)),
                ('fonction_signataire_rh', models.CharField(blank=True, default='Responsable recrutement', max_length=255)),
                ('date_signature_rh', models.DateField(blank=True, null=True)),
                ('signe_rh', models.BooleanField(default=False)),
                ('avis_manager', models.CharField(blank=True, choices=[('FAVORABLE', 'Favorable'), ('FAVORABLE_RESERVE', 'Favorable avec réserve'), ('DEFAVORABLE', 'Défavorable'), ('A_REVOIR', 'À revoir')], default='', max_length=30)),
                ('commentaire_manager', models.TextField(blank=True, default='')),
                ('nom_signataire_manager', models.CharField(blank=True, default='', max_length=255)),
                ('fonction_signataire_manager', models.CharField(blank=True, default='Manager', max_length=255)),
                ('date_signature_manager', models.DateField(blank=True, null=True)),
                ('signe_manager', models.BooleanField(default=False)),
                ('observation_generale', models.TextField(blank=True, default='')),
                ('decision_finale', models.CharField(blank=True, choices=[('RETENU', 'Retenu'), ('NON_RETENU', 'Non retenu'), ('A_REVOIR', 'À revoir')], default='', max_length=20)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('VALIDE', 'Validé'), ('ENVOYE', 'Envoyé au DRH')], db_index=True, default='BROUILLON', max_length=20)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('date_envoi', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('candidat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compte_rendu_cadre', to='recruitment.candidat')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comptes_rendus_cadres_crees', to='accounts.hrprofile')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comptes_rendus_cadres_valides', to='accounts.hrprofile')),
            ],
            options={
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['statut'], name='cr_cadre_statut_idx'), models.Index(fields=['date_entretien'], name='cr_cadre_entretien_idx')],
            },
        ),
    ]
