# Generated by Django 6.0.5 on 2026-09-02 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0007_demanderecrutement_type_recrutement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compterenduentretiencadre',
            name='decision_finale',
            field=models.CharField(blank=True, choices=[('RETENU', 'Retenu'), ('NON_RETENU', 'Non retenu')], default='', max_length=20),
        ),
    ]
