# Generated by Django 6.0.5 on 2026-09-02 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0008_alter_compterenduentretiencadre_decision_finale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='statut',
            field=models.CharField(choices=[('AJOUTE', 'Ajouté'), ('ENTRETIEN_PLANIFIE', 'Entretien planifié'), ('ENTRETIEN_REALISE', 'Entretien réalisé'), ('COMPTE_RENDU_BROUILLON', 'Compte rendu en brouillon'), ('COMPTE_RENDU_ENVOYE', 'Compte rendu envoyé'), ('RETENU', 'Retenu'), ('NON_RETENU', 'Non retenu'), ('NON_RECU', 'Non reçu'), ('RECU', 'Reçu'), ('EMBAUCHE', 'Embauché')], default='AJOUTE', max_length=30),
        ),
    ]
