# Generated by Django 6.0.5 on 2026-09-02 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_hrprofile_perm_cantine_read_and_more'),
        ('employees', '0019_cantinelist_cantinelistitem'),
        ('recruitment', '0009_alter_candidat_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidat',
            name='date_entretien_prevue',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidat',
            name='date_entretien_realisee',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='NotificationChargeRHSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinataires', models.JSONField(blank=True, default=list)),
                ('sujet', models.CharField(blank=True, default='', max_length=255)),
                ('message', models.TextField(blank=True, default='')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ENVOYEE', 'Envoyée'), ('ECHEC', 'Échec')], db_index=True, default='EN_ATTENTE', max_length=20)),
                ('erreur_envoi', models.TextField(blank=True, default='')),
                ('date_envoi', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('candidats', models.ManyToManyField(blank=True, related_name='notifications_charge_rh', to='recruitment.candidat')),
                ('envoye_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_recrutement_envoyees', to='accounts.hrprofile')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications_recrutement', to='employees.factory')),
                ('processus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_charge_rh', to='recruitment.processusrecrutement')),
            ],
            options={
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['processus', 'statut'], name='notif_rh_process_statut_idx')],
            },
        ),
    ]
