# Generated by Django 5.2.17 on 2026-09-02 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_hrprofile_perm_cantine_read_and_more'),
        ('recruitment', '0010_candidat_date_entretien_prevue_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TachePreparationEmbauche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('IT', 'Informatique'), ('COMPTABILITE', 'Comptabilité'), ('RH', 'Ressources humaines')], max_length=30)),
                ('type_tache', models.CharField(choices=[('CREATION_EMAIL', 'Création de l’adresse e-mail'), ('PREPARATION_MATERIEL', 'Préparation du matériel'), ('CREATION_ACCES', 'Création des accès et outils'), ('PREPARATION_BUREAU', 'Préparation du bureau'), ('COMMANDE_EQUIPEMENTS', 'Commande des équipements'), ('PREPARATION_CONTRAT', 'Préparation du contrat'), ('PREPARATION_INTEGRATION', 'Préparation de l’intégration')], max_length=40)),
                ('libelle', models.CharField(max_length=255)),
                ('statut', models.CharField(choices=[('A_FAIRE', 'À faire'), ('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée'), ('ANNULEE', 'Annulée')], db_index=True, default='A_FAIRE', max_length=20)),
                ('commentaire', models.TextField(blank=True, default='')),
                ('date_debut', models.DateTimeField(blank=True, null=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('notification_email_envoyee', models.BooleanField(default=False, verbose_name='Notification e-mail envoyée')),
                ('date_notification_email', models.DateTimeField(blank=True, null=True, verbose_name='Date de notification')),
                ('destinataires_notification', models.JSONField(blank=True, default=list, verbose_name='Destinataires de la notification')),
                ('erreur_notification', models.TextField(blank=True, default='', verbose_name='Erreur de notification')),
                ('nombre_tentatives_notification', models.PositiveIntegerField(default=0, verbose_name='Nombre de tentatives de notification')),
                ('assignee_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taches_preparation_embauche', to='accounts.hrprofile')),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taches_preparation_embauche', to='recruitment.candidat')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taches_preparation_creees', to='accounts.hrprofile')),
            ],
            options={
                'ordering': ['service', 'type_tache'],
                'indexes': [models.Index(fields=['service', 'statut'], name='tache_prep_service_statut_idx'), models.Index(fields=['candidat', 'statut'], name='tache_prep_candidat_statut_idx')],
                'constraints': [models.UniqueConstraint(fields=('candidat', 'type_tache'), name='unique_tache_preparation_par_candidat')],
            },
        ),
    ]
