# Generated by Django 6.0.5 on 2026-09-03 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_hrprofile_perm_cantine_read_and_more'),
        ('recruitment', '0011_tachepreparationembauche'),
    ]

    operations = [
        migrations.AddField(
            model_name='tachepreparationembauche',
            name='terminee_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taches_preparation_terminees', to='accounts.hrprofile'),
        ),
    ]
