# Generated by Django 6.0.5 on 2026-09-03 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_hrprofile_perm_cantine_read_and_more'),
        ('recruitment', '0012_tachepreparationembauche_terminee_par'),
    ]

    operations = [
        migrations.AddField(
            model_name='demanderecrutement',
            name='approuve_par_drh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_recrutement_approuvees_drh', to='accounts.hrprofile'),
        ),
        migrations.AddField(
            model_name='demanderecrutement',
            name='commentaire_drh',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='demanderecrutement',
            name='date_approbation_drh',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demanderecrutement',
            name='motif_decision',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='demanderecrutement',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EN_ATTENTE', 'En attente de validation du directeur'), ('EN_ATTENTE_DRH', 'En attente d’approbation du DRH'), ('VALIDEE', 'Approuvée par le DRH'), ('REFUSEE', 'Refusée (ancien statut)'), ('REFUSEE_DIRECTEUR', 'Refusée par le directeur'), ('REFUSEE_DRH', 'Refusée par le DRH'), ('TERMINEE', 'Terminée')], default='EN_ATTENTE', max_length=30),
        ),
    ]
