# Generated by Django 6.0.5 on 2026-09-04 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_hrprofile_perm_dashboard_read_and_more'),
        ('recruitment', '0013_demanderecrutement_approuve_par_drh_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='embauche',
            name='code_societe_communique',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='embauche',
            name='contrat_travail_signe',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='embauche',
            name='date_envoi_documents_cadre',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='embauche',
            name='destinataires_documents_cadre',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='embauche',
            name='documents_cadre_email_envoyes',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='embauche',
            name='dossier_embauche_complet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='embauche',
            name='erreur_envoi_documents_cadre',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='embauche',
            name='journee_integration_realisee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='embauche',
            name='nombre_tentatives_envoi_documents_cadre',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='embauche',
            name='reglement_interieur_communique',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='processusrecrutement',
            name='cloture_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processus_recrutement_clotures', to='accounts.hrprofile'),
        ),
        migrations.AddField(
            model_name='processusrecrutement',
            name='date_cloture',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
