# Generated by Django 6.0.5 on 2026-09-08 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_hrprofile_perm_recruitment_validate'),
        ('recruitment', '0014_embauche_code_societe_communique_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesistementEmbauche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_desistement', models.DateField()),
                ('motif', models.TextField(blank=True, default='')),
                ('commentaire', models.TextField(blank=True, default='')),
                ('relancer_recrutement', models.BooleanField(default=True)),
                ('date_reprise_recrutement', models.DateField(blank=True, null=True)),
                ('date_cloture_initiale', models.DateTimeField(blank=True, editable=False, null=True)),
                ('date_nouvelle_cloture', models.DateTimeField(blank=True, editable=False, null=True)),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
                ('embauche', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='desistement', to='recruitment.embauche')),
                ('enregistre_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='desistements_enregistres', to='accounts.hrprofile')),
            ],
            options={
                'ordering': ['-date_enregistrement'],
            },
        ),
    ]
