# Generated by Django 5.2.12 on 2026-03-20 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HRProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_user_id', models.IntegerField(help_text='User ID from django_auth', unique=True)),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('hr_role', models.CharField(choices=[('DIRECTOR', 'Directeur RH'), ('MANAGER_HR', 'Responsable RH'), ('ASSISTANT_HR', 'Assistant RH'), ('MANAGER', 'Manager')], default='ASSISTANT_HR', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managers', to='employees.department')),
                ('factory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managers', to='employees.factory')),
            ],
            options={
                'ordering': ['username'],
            },
        ),
    ]
