# Generated by Django 5.2.12 on 2026-03-21 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hrprofile',
            name='hr_role',
        ),
        migrations.AddField(
            model_name='hrprofile',
            name='is_director',
            field=models.BooleanField(default=False, help_text='Directeur RH — accès total'),
        ),
        migrations.AddField(
            model_name='hrprofile',
            name='job_title',
            field=models.CharField(blank=True, help_text='Ex: Gestionnaire Paie', max_length=100),
        ),
        migrations.AddField(
            model_name='hrprofile',
            name='perm_contracts_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hrprofile',
            name='perm_contracts_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hrprofile',
            name='perm_contracts_write',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hrprofile',
            name='perm_employees_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hrprofile',
            name='perm_employees_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hrprofile',
            name='perm_employees_write',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hrprofile',
            name='perm_hr_users_manage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hrprofile',
            name='perm_leaves_approve',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hrprofile',
            name='perm_leaves_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hrprofile',
            name='perm_leaves_write',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hrprofile',
            name='perm_pay_events_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hrprofile',
            name='perm_pay_events_write',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hrprofile',
            name='perm_payroll_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hrprofile',
            name='perm_payroll_validate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hrprofile',
            name='perm_payroll_write',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hrprofile',
            name='perm_recruitment_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hrprofile',
            name='perm_recruitment_write',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hrprofile',
            name='perm_reports_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hrprofile',
            name='perm_retraite_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hrprofile',
            name='perm_retraite_write',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hrprofile',
            name='perm_sanctions_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hrprofile',
            name='perm_sanctions_write',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hrprofile',
            name='perm_shifts_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hrprofile',
            name='perm_shifts_write',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hrprofile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_managers', to='employees.department'),
        ),
        migrations.AlterField(
            model_name='hrprofile',
            name='factory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_managers', to='employees.factory'),
        ),
    ]
