# Generated by Django 5.2.12 on 2026-03-21 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_hrprofile_hr_role_hrprofile_is_director_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrprofile',
            name='perm_organisation_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hrprofile',
            name='perm_organisation_write',
            field=models.BooleanField(default=False),
        ),
    ]
