# Generated by Django 5.2.12 on 2026-03-21 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_hrprofile_perm_organisation_read_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrprofile',
            name='perm_alerts_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hrprofile',
            name='perm_alerts_write',
            field=models.BooleanField(default=False),
        ),
    ]
