# Generated by Django 5.2.12 on 2026-03-21 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_hrprofile_perm_alerts_read_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrprofile',
            name='is_director',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hrprofile',
            name='job_title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
