# Generated by Django 5.2.12 on 2026-03-23 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_hrprofile_is_director_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrprofile',
            name='perm_hr_events_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hrprofile',
            name='perm_hr_events_write',
            field=models.BooleanField(default=False),
        ),
    ]
