# Generated by Django 5.2.13 on 2026-07-20 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_hrprofile_perm_audit_logs_read_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrprofile',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
