# Generated by Django 5.2.16 on 2026-07-28 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_hrprofile_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrprofile',
            name='perm_cantine_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hrprofile',
            name='perm_cantine_write',
            field=models.BooleanField(default=False),
        ),
    ]
