# Generated by Django 5.2.16 on 2026-08-18 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_hrprofile_perm_cantine_read_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrprofile',
            name='perm_dashboard_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hrprofile',
            name='perm_devices_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hrprofile',
            name='perm_devices_write',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hrprofile',
            name='perm_presence_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hrprofile',
            name='perm_presence_write',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hrprofile',
            name='perm_retard_read',
            field=models.BooleanField(default=False),
        ),
    ]
