# Generated by Django 5.2.17 on 2026-09-07 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_hrprofile_perm_dashboard_read_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrprofile',
            name='perm_recruitment_validate',
            field=models.BooleanField(default=False),
        ),
    ]
