# Generated by Django 5.2.17 on 2026-09-11 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_hrprofile_perm_recruitment_validate'),
        ('employees', '0019_cantinelist_cantinelistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrprofile',
            name='is_recruitment_responsible',
            field=models.BooleanField(default=False, verbose_name='Responsable du recrutement'),
        ),
        migrations.AddConstraint(
            model_name='hrprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('is_recruitment_responsible', True)), fields=('is_recruitment_responsible',), name='unique_recruitment_responsible'),
        ),
    ]
