# Generated by Django 5.2.17 on 2026-09-23 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_hrprofile_is_recruitment_responsible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrprofile',
            name='perm_recruitment_requests_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hrprofile',
            name='perm_recruitment_requests_write',
            field=models.BooleanField(default=False),
        ),
    ]
