# Generated by Django 5.2.17 on 2026-09-29 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_hrprofile_perm_recruitment_requests_read_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrprofile',
            name='perm_classification_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hrprofile',
            name='perm_classification_write',
            field=models.BooleanField(default=False),
        ),
    ]
