# Generated by Django 5.2.12 on 2026-03-21 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.TextField(blank=True, help_text='Adresse complète', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='affectation',
            field=models.CharField(blank=True, help_text='Affectation', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='birth_date',
            field=models.DateField(blank=True, help_text='Date de naissance', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='birth_place',
            field=models.CharField(blank=True, help_text='Lieu de naissance', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='cin',
            field=models.CharField(blank=True, help_text='Numéro CIN', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='cin_date',
            field=models.DateField(blank=True, help_text='Date CIN', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='cin_place',
            field=models.CharField(blank=True, help_text='Lieu de délivrance CIN', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='cnaps',
            field=models.CharField(blank=True, help_text='Numéro CNAPS', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='hk_ou_pbi',
            field=models.CharField(blank=True, help_text='HK ou PBI', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='matricule_paie',
            field=models.CharField(blank=True, help_text='Période de Paie embauche', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='motif_depart',
            field=models.CharField(blank=True, help_text='Intitulé du motif de départ', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='n_rh',
            field=models.CharField(blank=True, help_text='N° RH', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='nbre_enfants',
            field=models.IntegerField(blank=True, help_text="Nombre d'enfants", null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='sexe',
            field=models.CharField(blank=True, help_text='Sexe (M/F)', max_length=10, null=True),
        ),
    ]
