# Generated by Django 5.2.12 on 2026-04-06 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_employee_classification_employee_salaire_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Human label, e.g. 'Maternity', 'Afternoon Shift', 'Part-Time'", max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('work_start', models.TimeField(help_text='Employee is considered LATE if they arrive after this time. e.g. 07:40')),
                ('standard_start', models.TimeField(help_text='Official start of the workday for hours calculation. e.g. 07:30')),
                ('standard_end', models.TimeField(help_text='Official end of the workday. e.g. 16:30')),
                ('early_leave_limit', models.TimeField(help_text='Employee is considered to have left EARLY if departure is before this. e.g. 16:27')),
                ('lunch_start', models.TimeField(default='12:00', help_text='Start of unpaid lunch break.')),
                ('lunch_end', models.TimeField(default='13:00', help_text='End of unpaid lunch break.')),
                ('standard_work_hours', models.FloatField(default=8.0, help_text='Effective work hours per day after lunch deduction.')),
                ('overtime_threshold_hours', models.FloatField(default=8.5, help_text='Hours worked beyond this count as overtime.')),
                ('valid_from', models.DateField(blank=True, help_text='Schedule is active from this date. Leave blank for no start limit.', null=True)),
                ('valid_until', models.DateField(blank=True, help_text='Schedule expires after this date. Leave blank for no end limit.', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, help_text='Applies to all employees in this department (unless overridden by section/employee).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_schedules', to='employees.department')),
                ('employee', models.ForeignKey(blank=True, help_text='Assign directly to a single employee.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_schedules', to='employees.employee')),
                ('section', models.ForeignKey(blank=True, help_text='Applies to all employees in this section (unless overridden by employee).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_schedules', to='employees.section')),
            ],
            options={
                'verbose_name': 'Work Schedule',
                'verbose_name_plural': 'Work Schedules',
                'ordering': ['name'],
            },
        ),
    ]
