# Generated by Django 5.2.12 on 2026-04-07 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_workschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('time_from', models.TimeField(help_text='Access allowed from this time')),
                ('time_to', models.TimeField(help_text='Access allowed until this time')),
                ('days_of_week', models.CharField(default='MON,TUE,WED,THU,FRI', help_text='Comma-separated day codes: MON,TUE,WED,THU,FRI,SAT,SUN', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Access Time Slot',
                'verbose_name_plural': 'Access Time Slots',
                'ordering': ['time_from', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AccessZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, help_text='Physical location description', max_length=200)),
                ('device_id', models.IntegerField(blank=True, help_text='ZKTeco device ID controlling this zone', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Access Zone',
                'verbose_name_plural': 'Access Zones',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeAccessRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateField(blank=True, help_text='Rule active from this date (blank = always)', null=True)),
                ('valid_until', models.DateField(blank=True, help_text='Rule expires after this date (blank = never)', null=True)),
                ('notes', models.TextField(blank=True, help_text='Reason or notes for this rule')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, help_text='HR user who created this rule', max_length=100)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_rules', to='employees.employee')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_rules', to='employees.accesstimeslot')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_rules', to='employees.accesszone')),
            ],
            options={
                'verbose_name': 'Employee Access Rule',
                'verbose_name_plural': 'Employee Access Rules',
                'ordering': ['employee', 'zone', 'time_slot'],
                'unique_together': {('employee', 'zone', 'time_slot')},
            },
        ),
    ]
