# Generated by Django 5.2.13 on 2026-06-15 06:04
from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_nullable_factory_department'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(model_name='department', name='code'),
                migrations.RemoveField(model_name='factory',    name='code'),
                migrations.RemoveField(model_name='section',    name='code'),
            ],
        ),
    ]
