# Generated by Django 5.2.13 on 2026-06-15 06:33
from django.db import migrations

class Migration(migrations.Migration):
    dependencies = [
        ('employees', '0012_remove_code_fields'),
    ]
    operations = [
        migrations.RunSQL(
            "ALTER TABLE employees_factory DROP COLUMN IF EXISTS code;",
            reverse_sql="SELECT 1;",
        ),
        migrations.RunSQL(
            "ALTER TABLE employees_section DROP COLUMN IF EXISTS code;",
            reverse_sql="SELECT 1;",
        ),
    ]
