# Generated by Django 5.2.16 on 2026-07-18 13:26
# Edited: removed duplicate CreateModel/AddField ops already present in
# 0016_transportlist_department_code_departement_and_more, to fix
# "relation already exists" errors on fresh databases.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0016_transportlist_department_code_departement_and_more'),
        ('employees', '0016_fix_classification_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='classification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='employees.classification'),
        ),
    ]
