# Generated by Django 5.2.16 on 2026-07-18 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0016_transportlist_department_code_departement_and_more'),
        ('employees', '0017_transportlist_department_code_departement_and_more'),
    ]

    operations = [
    ]
