# Generated by Django 5.2.16 on 2026-07-22 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0018_merge_20260719_0022'),
    ]

    operations = [
        migrations.CreateModel(
            name='CantineList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantine_date', models.DateField(unique=True)),
                ('created_by', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-cantine_date'],
            },
        ),
        migrations.CreateModel(
            name='CantineListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(blank=True, max_length=100)),
                ('nom', models.CharField(blank=True, max_length=255)),
                ('prenom', models.CharField(blank=True, max_length=255)),
                ('arrival', models.DateTimeField(blank=True, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('cantine_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='employees.cantinelist')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employee')),
            ],
            options={
                'ordering': ['nom', 'prenom'],
                'unique_together': {('cantine_list', 'employee')},
            },
        ),
    ]
