# Generated by Django 5.2.12 on 2026-03-16 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transport_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('housing_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('meal_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('employee_social_charge_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('employer_social_charge_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to='employees.employee')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payroll.salarystructure')),
            ],
            options={
                'ordering': ['-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_month', models.PositiveIntegerField()),
                ('period_year', models.PositiveIntegerField()),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('allowances', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bonuses', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('overtime_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('social_charges', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('worked_days', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('absent_days', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('leave_days', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('VALIDATED', 'Validated'), ('PAID', 'Paid')], default='DRAFT', max_length=20)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('validated_by', models.IntegerField(blank=True, null=True)),
                ('paid_at', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to='employees.employee')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payroll.salarystructure')),
            ],
            options={
                'ordering': ['-period_year', '-period_month'],
                'unique_together': {('employee', 'period_month', 'period_year')},
            },
        ),
    ]
