"""Remove status, punch, and created_at from attendance

Revision ID: 43b7bd5b0afc
Revises: d1efb039ea56
Create Date: 2025-09-01 14:32:00.314175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '43b7bd5b0afc'
down_revision: Union[str, Sequence[str], None] = 'd1efb039ea56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendance', 'created_at')
    op.drop_column('attendance', 'status')
    op.drop_column('attendance', 'punch')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('punch', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('attendance', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('attendance', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
