"""Add device_ip column to attendance table

Revision ID: 68e11999c2f6
Revises: bf92f68d27ca
Create Date: 2025-08-28 15:40:23.255595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68e11999c2f6'
down_revision: Union[str, Sequence[str], None] = 'bf92f68d27ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('device_ip', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendance', 'device_ip')
    # ### end Alembic commands ###
