# Generated by Django 5.2.12 on 2026-03-23 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0005_employee_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='HREventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('category', models.CharField(choices=[('ABSENCE', 'Absence'), ('LEAVE', 'Congé'), ('PERMISSION', 'Permission'), ('MEDICAL', 'Médical'), ('DEPARTURE', 'Départ'), ('OTHER', 'Autre')], default='OTHER', max_length=20)),
                ('is_paid', models.BooleanField(default=True)),
                ('affects_status', models.BooleanField(default=False, help_text='If True, changes employee status when event is active')),
                ('target_status', models.CharField(blank=True, help_text='Employee status to set when event is active (e.g. TERMINATED)', max_length=20)),
                ('color', models.CharField(default='#6B7280', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HREvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('duration_hours', models.DecimalField(blank=True, decimal_places=1, help_text='For hour-based permissions', max_digits=6, null=True)),
                ('reason', models.TextField(blank=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='hr_events/documents/')),
                ('status', models.CharField(choices=[('ACTIVE', 'Actif'), ('CLOSED', 'Clôturé'), ('CANCELLED', 'Annulé')], default='ACTIVE', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_by', models.IntegerField(help_text='Auth user ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_events', to='employees.employee')),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='hr_events.hreventtype')),
            ],
            options={
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['employee', 'status'], name='hr_events_h_employe_03fc3b_idx'), models.Index(fields=['start_date', 'end_date'], name='hr_events_h_start_d_458b84_idx'), models.Index(fields=['event_type'], name='hr_events_h_event_t_975903_idx')],
            },
        ),
    ]
