# Generated by Django 5.2.12 on 2026-03-21 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='CDDAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termination_date', models.DateField()),
                ('days_remaining', models.IntegerField()),
                ('alert_threshold', models.IntegerField(help_text='Alert sent at X days before expiry')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('SENT', 'Envoyé'), ('RENEWED', 'Renouvelé'), ('EXPIRED', 'Expiré'), ('IGNORED', 'Ignoré')], default='PENDING', max_length=20)),
                ('email_sent_to', models.EmailField(blank=True, max_length=254)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cdd_alerts', to='employees.employee')),
            ],
            options={
                'ordering': ['termination_date'],
                'unique_together': {('employee', 'alert_threshold')},
            },
        ),
    ]
