# Generated by Django 5.2.12 on 2026-03-21 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
        ('employees', '0002_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='CDDNotificationAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_user_id', models.IntegerField(help_text='HR user ID from HRProfile')),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cdd_notified_users', to='employees.department')),
                ('factory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cdd_notified_users', to='employees.factory')),
            ],
            options={
                'ordering': ['username'],
                'unique_together': {('auth_user_id', 'factory', 'department')},
            },
        ),
    ]
