# Generated by Django 5.2.12 on 2026-03-31 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_cddnotificationassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='InAppNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_user_id', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Attention'), ('error', 'Erreur'), ('success', 'Succes')], default='info', max_length=10)),
                ('category', models.CharField(choices=[('cdd', 'Alerte CDD'), ('leave', 'Conge'), ('maternity', 'Maternite'), ('employee', 'Employe'), ('system', 'Systeme')], default='system', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
