# Generated by Django 5.2.16 on 2026-08-25 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_inappnotification'),
        ('employees', '0019_cantinelist_cantinelistitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='LateAlertAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(blank=True, default='', max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='late_alert_assignments', to='employees.factory')),
            ],
            options={
                'verbose_name': 'Destinataire alerte retards',
                'verbose_name_plural': 'Destinataires alertes retards',
                'unique_together': {('factory', 'email')},
            },
        ),
    ]
