# Generated by Django 5.2.16 on 2026-08-26 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0004_latealertassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='latealertassignment',
            name='recipient_type',
            field=models.CharField(choices=[('to', 'À (To)'), ('cc', 'Cc')], default='to', max_length=3),
        ),
    ]
