# Generated by Django 5.2.17 on 2026-09-09 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0005_latealertassignment_recipient_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyLateReportAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(blank=True, default='', max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Destinataire rapport mensuel HC',
                'verbose_name_plural': 'Destinataires rapport mensuel HC',
                'ordering': ['email'],
            },
        ),
    ]
