# Generated by Django 5.2.13 on 2026-06-15 10:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClockerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Group name (e.g., 'F1', 'Factory', 'Warehouse')", max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of this group')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'devices_clocker_group',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Clocker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specific_name', models.CharField(blank=True, default='', help_text="Specific name (e.g., 'transit', 'entrance', 'exit')", max_length=90)),
                ('name', models.CharField(blank=True, editable=False, max_length=100)),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('port', models.IntegerField(default=4370)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(blank=True, help_text='Select the group for this clocker', null=True, on_delete=django.db.models.deletion.PROTECT, to='devices.clockergroup')),
            ],
            options={
                'db_table': 'devices_clocker',
                'ordering': ['name'],
            },
        ),
    ]
