# Generated by Django 5.2.17 on 2026-09-18 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clocker',
            name='is_permission_clocker',
            field=models.BooleanField(default=False, help_text='Si coché, ce clocker est dédié aux permissions en heure : chaque pointage impair = sortie, pair = retour. Le sync_service traite ses logs différemment des clockers standards (badge classique arrivée/départ).'),
        ),
    ]
