# Generated by Django 5.2.11 on 2026-02-18 11:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_alter_clocker_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClockerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Group name (e.g., 'F1', 'Factory', 'Warehouse')", max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of this group')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'devices_clocker_group',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='clocker',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='clocker',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='clocker',
            name='specific_name',
            field=models.CharField(blank=True, default='', help_text="Specific name (e.g., 'transit', 'entrance', 'exit')", max_length=90),
        ),
        migrations.AddField(
            model_name='clocker',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='clocker',
            name='ip_address',
            field=models.GenericIPAddressField(unique=True),
        ),
        migrations.AlterField(
            model_name='clocker',
            name='name',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='clocker',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Select the group for this clocker', null=True, on_delete=django.db.models.deletion.PROTECT, to='devices.clockergroup'),
        ),
    ]
