# Generated by Django 6.0.5 on 2026-07-15 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Création'), ('UPDATE', 'Modification'), ('DELETE', 'Suppression'), ('APPROVE', 'Approbation'), ('REJECT', 'Rejet')], max_length=10),
        ),
    ]
