# Generated by Django 6.0.5 on 2026-09-07 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_log', '0002_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Création'), ('UPDATE', 'Modification'), ('DELETE', 'Suppression'), ('APPROVE', 'Approbation'), ('REJECT', 'Rejet'), ('VALIDATE', 'Validation'), ('APPROVE_DRH', 'Approbation DRH'), ('REJECT_DRH', 'Rejet DRH'), ('STEP_DONE', 'Étape terminée'), ('CR_CREATE', 'Compte rendu créé'), ('CR_UPDATE', 'Compte rendu modifié'), ('CR_DELETE', 'Compte rendu supprimé'), ('CR_PDF', 'Compte rendu téléchargé'), ('CR_SEND', 'Compte rendu envoyé'), ('INT_PLAN', 'Entretien planifié'), ('INT_DONE', 'Entretien réalisé'), ('TEST_DEL', 'Fiche de test supprimée'), ('MAIL_RETRY', 'Notification renvoyée')], max_length=30),
        ),
    ]
