# Generated by Django 5.2.12 on 2026-03-21 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_section'),
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaternityLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_birth_date', models.DateField(help_text="Date prévue d'accouchement")),
                ('actual_birth_date', models.DateField(blank=True, help_text="Date réelle d'accouchement", null=True)),
                ('leave_start_date', models.DateField()),
                ('leave_end_date', models.DateField(help_text='Date fin légale (98 jours)')),
                ('extended_end_date', models.DateField(blank=True, help_text='Date fin si prolongation', null=True)),
                ('actual_return_date', models.DateField(blank=True, help_text='Date réelle de reprise', null=True)),
                ('status', models.CharField(choices=[('DECLARED', 'Déclarée'), ('ON_LEAVE', 'En congé'), ('EXTENDED', 'Prolongée'), ('RETURNED', 'Reprise travail'), ('CANCELLED', 'Annulée')], default='DECLARED', max_length=20)),
                ('medical_document', models.FileField(blank=True, null=True, upload_to='leaves/maternity/')),
                ('note', models.TextField(blank=True)),
                ('alert_birth_sent', models.BooleanField(default=False)),
                ('alert_end_sent', models.BooleanField(default=False)),
                ('alert_return_sent', models.BooleanField(default=False)),
                ('created_by', models.IntegerField(help_text='Auth user ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maternity_leaves', to='employees.employee')),
            ],
            options={
                'ordering': ['-leave_start_date'],
            },
        ),
    ]
