# Generated by Django 5.2.16 on 2026-07-18 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0002_maternityleave'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='duration_hours',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Durée en heures, utilisé uniquement pour les permissions en heure (type PERH).', max_digits=4, null=True),
        ),
    ]
