# Generated by Django 5.2.16 on 2026-09-02 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0003_leaverequest_duration_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='is_protected',
            field=models.BooleanField(default=False, help_text='If True, this type cannot be deleted through the app (API or admin).'),
        ),
    ]
