# Generated by Django 6.0.5 on 2026-09-07 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0004_leavetype_is_protected'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='end_time',
            field=models.TimeField(blank=True, help_text='Heure de fin, uniquement pour une permission en heure.', null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='start_time',
            field=models.TimeField(blank=True, help_text='Heure de début, uniquement pour une permission en heure.', null=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='duration_hours',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Durée calculée en heures pour une permission en heure.', max_digits=5, null=True),
        ),
    ]
