# Generated by Django 6.0.5 on 2026-09-07 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0019_cantinelist_cantinelistitem'),
        ('leaves', '0005_leaverequest_end_time_leaverequest_start_time_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='leaverequest',
            name='leaves_leav_employe_7236fb_idx',
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='end_time',
            field=models.TimeField(blank=True, help_text='Heure de fin pour une permission en heure.', null=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='start_time',
            field=models.TimeField(blank=True, help_text='Heure de début pour une permission en heure.', null=True),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['employee'], name='leaves_leav_employe_c71dee_idx'),
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='rejection_reason',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='status',
        ),
    ]
