# Generated by Django 5.2.17 on 2026-09-18 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0006_remove_leaverequest_leaves_leav_employe_7236fb_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='auto_generated',
            field=models.BooleanField(default=False, help_text='True si cet événement a été créé automatiquement à partir du clocker de permissions (sortie/retour), plutôt que saisi manuellement par les RH.'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='source_attendance_in_id',
            field=models.PositiveIntegerField(blank=True, help_text='ID du pointage de retour source (table attendance, FastAPI). Unique : empêche de créer deux fois le même événement si le job repasse dessus.', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='source_attendance_out_id',
            field=models.PositiveIntegerField(blank=True, help_text='ID du pointage de sortie source (table attendance, FastAPI) — informatif uniquement.', null=True),
        ),
    ]
