# Generated by Django 5.2.17 on 2026-09-18 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0007_leaverequest_auto_generated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='source_attendance_out_id',
            field=models.PositiveIntegerField(blank=True, help_text="ID du pointage de sortie source (table attendance, FastAPI). Unique : empêche d'ouvrir deux fois le même événement pour la même sortie.", null=True, unique=True),
        ),
    ]
