# Generated by Django 5.2.17 on 2026-09-19 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0008_alter_leaverequest_source_attendance_out_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='source_attendance_in_id',
            field=models.PositiveBigIntegerField(blank=True, help_text='ID du pointage de retour source (table attendance, FastAPI). Unique : empêche de créer deux fois le même événement si le job repasse dessus.', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='source_attendance_out_id',
            field=models.PositiveBigIntegerField(blank=True, help_text="ID du pointage de sortie source (table attendance, FastAPI). Unique : empêche d'ouvrir deux fois le même événement pour la même sortie.", null=True, unique=True),
        ),
    ]
