[pytest]
DJANGO_SETTINGS_MODULE = config.test_settings
python_files = tests/*/test_*.py tests/test_*.py
python_classes = Test*
python_functions = test_*
addopts = --ds=config.test_settings --cov=. --cov-report=term-missing --cov-fail-under=75 --ignore=tests/test_api_integration.py --ignore=tests/test_employee_models.py --ignore=tests/test_payroll_models.py --ignore=tests/test_user_auth.py

[coverage:run]
omit =
    tests/*
    manage.py
    */migrations/*
    config/wsgi.py

[coverage:report]
omit =
    tests/*
    manage.py
    */migrations/*
    config/wsgi.py