# Generated by Django 5.2.12 on 2026-03-23 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0005_employee_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='SanctionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('level', models.PositiveSmallIntegerField(default=1, help_text='1=mineur … 5=grave')),
                ('color', models.CharField(default='#F59E0B', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Sanction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reason', models.TextField()),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CANCELLED', 'Annulée'), ('APPEALED', 'En appel')], default='ACTIVE', max_length=20)),
                ('created_by', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanctions', to='employees.employee')),
                ('sanction_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sanctions', to='sanctions.sanctiontype')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
